name: fb_scraper
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.9
  - pip
  - pandas
  - requests
  - pip:
      - facebook-scraper
      - lxml_html_clean
      - undetected-chromedriver